name: amazon_flutter
description: Amazon app in flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  provider: ^6.0.1
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  get_it: ^7.2.0
  flutterfire_ui: ^0.3.0
  count_stepper: ^0.0.4
  getwidget: ^2.0.4
  flutter_rating_bar: ^4.0.0
  firebase_database: ^9.0.4
  cloud_firestore: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
